baseURL = "http://catchance.github.io"
languageCode = "en-us"
title = "catchance"
theme = "smart"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

hasCJKLanguage = true

preserveTaxonomyNames = true

pygmentsCodeFences = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2011
    author = "catchance"                           # Author's name
#    avatar = "/img/avatar.png"           # Author's avatar
    subtitle = "Talk is cheap, Show me the code... "         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""
    license= ''
#    canvasNest = true

[params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

[params.social]
    GitHub = "catchance"
#    Twitter = "xxoo"
#    Instagram = "catchancex"
#    Weibo = "xxchance"
#    Wechat = "/img/wechat.jpg"  # Wechat QRcode image
    Email   = "catchance@163.com"
#    Facebook = "xxoo"
#    Telegram = "xxoo"
#    Dribbble = "xxoo"
#    Medium = "xxoo"

[outputs]
    home = ["JSON", "HTML"]
#    section = ["JSON", "HTML"]
